version: '3'

services:
  thedb:
    image: postgres
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - TZ='America/Sao_Paulo'
    ports:
      - "5432:5432"